export const LOAD_TASKS = "LOAD_TASKS";
export const GET_TASKS = "GET_TASKS";
export const LOAD_SAVE_TASKS = "LOAD_SAVE_TASKS";
export const LOAD_UPDATE_STATUS_TASK = "LOAD_UPDATE_STATUS_TASK";
export const ERROR_TASK = 'ERROR_TASK';
export const CLEAR_ERROR_TASK = 'CLEAR_ERROR_TASK';